### ISSUE TITLE
control board

### ISSUE THREAD

**Issue by xrust83** [HomeKidd/ESP8266-HomeKit-WeatherUnderGround-PWS#3]
For this project, you need to solder to the Wemos D1 mini or ESP-12 board. Or is it universal?
Для этого проекта нужно впаять на плату Wemos D1 mini или ESP-12. Или она универсальная?

**Comment by HomeKidd** [comment]
Sorry but i can't speak Russian 😂 

This project is based on ESP8266, so its not universal. You can solder pin headers to use it with Wemos **OR** solder an ESP8266 based board directly. Its  up to you which one you prefer 😄 

Also i have to mention that i have a newer version of this project with much more functions which will be available soon.

Take a look at my instagram:

[Picture 1](https://www.instagram.com/p/CF4dAufDaLd)
[Picture 2](https://www.instagram.com/p/CF1jBNZDV4o)
[Picture 3](https://www.instagram.com/p/CF9Y39HDV8G)

**Comment by xrust83** [comment]
Yes, I saw a mention of a new project in the wiki header. I figured out how to solder from the 3rd photo. Thank you
